# Generated by Django 3.2.15 on 2022-09-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='project name', max_length=100, verbose_name='project name')),
                ('code', models.CharField(help_text='project code', max_length=10, verbose_name='project code')),
                ('description', models.TextField(help_text='project description', max_length=1000, verbose_name='project description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='permission name', max_length=30, verbose_name='permission name')),
                ('can_view', models.BooleanField(help_text='view permission', verbose_name='view permission')),
                ('can_participate', models.BooleanField(help_text='moderator permission', verbose_name='moderator permission')),
                ('can_moderate', models.BooleanField(help_text='moderator permission', verbose_name='moderator permission')),
            ],
            options={
                'verbose_name': 'ProjectPermission',
                'verbose_name_plural': 'ProjectPermission',
                'ordering': ('project',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='status name', max_length=15, verbose_name='status name')),
            ],
            options={
                'verbose_name': 'ProjectTaskStatus',
                'verbose_name_plural': 'ProjectTaskStatus',
                'ordering': ('project',),
            },
        ),
        migrations.CreateModel(
            name='ProjectUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(help_text='relater project permission', on_delete=django.db.models.deletion.CASCADE, related_name='all_user_permissions', to='projects.projectpermission', verbose_name='relater project permission')),
                ('project', models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='project_user_permissions', to='projects.project', verbose_name='related project')),
            ],
            options={
                'verbose_name': 'ProjectUserPermission',
                'verbose_name_plural': 'ProjectUserPermission',
                'ordering': ('id',),
            },
        ),
    ]
