# Generated by Django 3.2.15 on 2022-09-24 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='project name', max_length=100, unique=True, verbose_name='project name')),
                ('code', models.CharField(help_text='project code', max_length=10, unique=True, verbose_name='project code')),
                ('description', models.TextField(help_text='project description', max_length=1000, verbose_name='project description')),
                ('creator', models.ForeignKey(help_text='project creator', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='project creator')),
                ('owner', models.ForeignKey(blank=True, help_text='project owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='project owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Project',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='permission name', max_length=30, verbose_name='permission name')),
                ('permission', models.CharField(choices=[('VIEWER', 'VIEWER'), ('PARTICIPANT', 'PARTICIPANT'), ('MODERATOR', 'MODERATOR'), ('ADMINISTRATOR', 'ADMINISTRATOR')], max_length=50)),
                ('project', models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.project', verbose_name='related project')),
            ],
            options={
                'verbose_name': 'ProjectPermission',
                'verbose_name_plural': 'ProjectPermission',
                'ordering': ('project', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProjectUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(help_text='project permission', on_delete=django.db.models.deletion.CASCADE, related_name='project_user_permissions', to='projects.projectpermission', verbose_name='project permission')),
                ('project', models.ForeignKey(help_text='project', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='projects.project', verbose_name='project')),
                ('user', models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ProjectUserPermission',
                'verbose_name_plural': 'ProjectUserPermission',
                'ordering': ('user', 'project'),
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='status name', max_length=15, verbose_name='status name')),
                ('order_number', models.PositiveSmallIntegerField(help_text='status order number', verbose_name='status order number')),
                ('project', models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='projects.project', verbose_name='related project')),
            ],
            options={
                'verbose_name': 'ProjectTaskStatus',
                'verbose_name_plural': 'ProjectTaskStatus',
                'ordering': ('project', 'order_number'),
            },
        ),
        migrations.AddConstraint(
            model_name='projectuserpermission',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project'),
        ),
        migrations.AddConstraint(
            model_name='projectpermission',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_name_project'),
        ),
    ]
