# Generated by Django 3.2.15 on 2022-09-20 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuserpermission',
            name='user',
            field=models.ForeignKey(help_text='relater user', on_delete=django.db.models.deletion.CASCADE, related_name='user_project_permissions', to=settings.AUTH_USER_MODEL, verbose_name='related user'),
        ),
        migrations.AddField(
            model_name='projecttaskstatus',
            name='project',
            field=models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='projects.project', verbose_name='related project'),
        ),
        migrations.AddField(
            model_name='projectpermission',
            name='project',
            field=models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.project', verbose_name='related project'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='project creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='project creator'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='project owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='project owner'),
        ),
    ]
