# Generated by Django 3.2.15 on 2022-09-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpermission',
            name='permission',
            field=models.CharField(choices=[('VIEWER', 'VIEWER'), ('PARTICIPANT', 'PARTICIPANT'), ('ADMINISTRATOR', 'ADMINISTRATOR')], max_length=50),
        ),
    ]
