# Generated by Django 3.2.15 on 2022-09-22 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpermission',
            options={'ordering': ('project', 'id'), 'verbose_name': 'ProjectPermission', 'verbose_name_plural': 'ProjectPermission'},
        ),
        migrations.AlterModelOptions(
            name='projecttaskstatus',
            options={'ordering': ('project', 'id'), 'verbose_name': 'ProjectTaskStatus', 'verbose_name_plural': 'ProjectTaskStatus'},
        ),
        migrations.AlterModelOptions(
            name='projectuserpermission',
            options={'ordering': ('user', 'project'), 'verbose_name': 'ProjectUserPermission', 'verbose_name_plural': 'ProjectUserPermission'},
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='project code', max_length=10, unique=True, verbose_name='project code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='project name', max_length=100, unique=True, verbose_name='project name'),
        ),
        migrations.AlterField(
            model_name='projectpermission',
            name='can_participate',
            field=models.BooleanField(help_text='participant permission', verbose_name='participant permission'),
        ),
        migrations.AlterField(
            model_name='projectuserpermission',
            name='permission',
            field=models.ForeignKey(help_text='project permission', on_delete=django.db.models.deletion.CASCADE, related_name='project_user_permissions', to='projects.projectpermission', verbose_name='project permission'),
        ),
        migrations.AlterField(
            model_name='projectuserpermission',
            name='project',
            field=models.ForeignKey(help_text='project', on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='projects.project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='projectuserpermission',
            name='user',
            field=models.ForeignKey(help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='project_permissions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddConstraint(
            model_name='projectpermission',
            constraint=models.UniqueConstraint(fields=('name', 'project'), name='unique_name_project'),
        ),
        migrations.AddConstraint(
            model_name='projectuserpermission',
            constraint=models.UniqueConstraint(fields=('user', 'project'), name='unique_user_project'),
        ),
    ]
