# Generated by Django 3.2.15 on 2022-09-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='project name', max_length=100, verbose_name='project name')),
                ('code', models.CharField(help_text='project code', max_length=10, verbose_name='project code')),
                ('description', models.TextField(help_text='project description', max_length=1000, verbose_name='project description')),
                ('creator', models.ForeignKey(blank=True, help_text='project creator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='project creator')),
                ('owner', models.ForeignKey(blank=True, help_text='project owner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='project owner')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='status name', max_length=15, verbose_name='status name')),
                ('project', models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='tasks.project', verbose_name='related project')),
            ],
            options={
                'verbose_name': 'ProjectTaskStatus',
                'verbose_name_plural': 'ProjectTaskStatus',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='task name', max_length=100, verbose_name='task name')),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date created', verbose_name='date created')),
                ('deadline', models.DateTimeField(blank=True, help_text='task deadline', null=True, verbose_name='task deadline')),
                ('text', models.TextField(blank=True, help_text='task description', max_length=1000, null=True, verbose_name='task description')),
                ('creator', models.ForeignKey(help_text='task creator', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='task creator')),
                ('executor', models.ForeignKey(help_text='task executor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='task executor')),
                ('project', models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='related project')),
                ('status', models.ForeignKey(blank=True, help_text='task status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.projecttaskstatus', verbose_name='task status')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TaskLogTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DurationField(db_index=True, help_text='time spent', verbose_name='time spent')),
                ('log_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='log date', verbose_name='log date')),
                ('comment', models.TextField(blank=True, help_text='comment', max_length=1000, null=True, verbose_name='comment')),
                ('task', models.ForeignKey(help_text='related task', on_delete=django.db.models.deletion.CASCADE, related_name='logged_time', to='tasks.task', verbose_name='related task')),
                ('user', models.ForeignKey(help_text='executor', on_delete=django.db.models.deletion.CASCADE, related_name='logged_time', to=settings.AUTH_USER_MODEL, verbose_name='executor')),
            ],
            options={
                'verbose_name': 'TaskLogTime',
                'verbose_name_plural': 'TaskLogTime',
                'ordering': ('id',),
            },
        ),
    ]
