# Generated by Django 3.2.15 on 2022-08-27 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='task name', max_length=100, verbose_name='task name')),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date created', verbose_name='date created')),
                ('deadline', models.DateTimeField(blank=True, help_text='task deadline', null=True, verbose_name='task deadline')),
                ('text', models.TextField(blank=True, help_text='task description', max_length=1000, null=True, verbose_name='task description')),
                ('creator', models.ForeignKey(help_text='task creator', on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='task creator')),
                ('executor', models.ForeignKey(help_text='task executor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='task executor')),
            ],
        ),
    ]
