# Generated by Django 3.2.15 on 2022-09-18 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskLoggedTime',
            new_name='TaskLogTime',
        ),
    ]
