# Generated by Django 3.2.15 on 2022-09-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='task name', max_length=100, verbose_name='task name')),
                ('priority', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH')], max_length=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date created', verbose_name='date created')),
                ('deadline', models.DateTimeField(blank=True, help_text='task deadline', null=True, verbose_name='task deadline')),
                ('text', models.TextField(blank=True, help_text='task description', max_length=1000, null=True, verbose_name='task description')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TaskLogTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.DurationField(db_index=True, help_text='time spent', verbose_name='time spent')),
                ('log_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='log date', verbose_name='log date')),
                ('comment', models.TextField(blank=True, help_text='comment', max_length=1000, null=True, verbose_name='comment')),
                ('task', models.ForeignKey(help_text='related task', on_delete=django.db.models.deletion.CASCADE, related_name='logged_time', to='tasks.task', verbose_name='related task')),
            ],
            options={
                'verbose_name': 'TaskLogTime',
                'verbose_name_plural': 'TaskLogTime',
                'ordering': ('id',),
            },
        ),
    ]
