# Generated by Django 3.2.15 on 2022-09-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttaskstatus',
            name='project',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(help_text='related project', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='related project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(blank=True, help_text='task status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projecttaskstatus', verbose_name='task status'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectTaskStatus',
        ),
    ]
