# Generated by Django 3.2.15 on 2022-09-22 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='executor',
        ),
        migrations.CreateModel(
            name='TaskAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.ForeignKey(help_text='assignee', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to=settings.AUTH_USER_MODEL, verbose_name='assignee')),
                ('task', models.ForeignKey(help_text='task', on_delete=django.db.models.deletion.CASCADE, related_name='task_assignees', to='tasks.task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'TaskAssignee',
                'verbose_name_plural': 'TaskAssignee',
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='taskassignee',
            constraint=models.UniqueConstraint(fields=('task', 'assignee'), name='unique_task_assignee'),
        ),
    ]
